# build_toc.py
import argparse
import shutil
import subprocess
import yaml
from pathlib import Path

CONFIG_FILE = Path("journal.yml")
NEXUS_DIR = Path("nexus")
TOC_FILE = NEXUS_DIR / "_toc.yml"
CONTENT_DIR = Path("content/papers")

TOC_HEADER = """
# This file is auto-generated by build_toc.py. DO NOT EDIT.
format: jb-book
root: home
parts:
  - caption: Static
    chapters:
      - file: content/static/01-paper.md
      - file: content/static/02-justtext.md
      - file: content/static/03-notebook.ipynb
  - caption: Journal Papers
    chapters:
"""


def clone_repo(repo_url, clone_path):
    """Clones a repo into a specific path."""
    print(f"Cloning {repo_url} into {clone_path}...")
    subprocess.run(
        ["git", "clone", "--depth", "1", repo_url, str(clone_path)],
        check=True,
        capture_output=True,
    )


def setup_papers_dir():
    """Cleans and creates the content directory for papers."""
    papers_dir = NEXUS_DIR / CONTENT_DIR
    if papers_dir.exists():
        shutil.rmtree(papers_dir)
    papers_dir.mkdir(parents=True, exist_ok=True)


def generate_toc():
    """Generates _toc.yml from journal.yml and clones repos."""

    parser = argparse.ArgumentParser(
        description="Clone repos and build TOC for the journal."
    )
    parser.add_argument(
        "--dev",
        action="store_true",
        help="Run in DEV mode: only clones the first paper for a fast build.",
    )
    args = parser.parse_args()

    setup_papers_dir()

    toc_content = [TOC_HEADER.strip()]

    with open(CONFIG_FILE, "r") as f:
        config = yaml.safe_load(f)

    papers_to_process = config.get("papers", [])

    if args.dev:
        print("Running in DEV mode. Only processing the first paper.")
        if papers_to_process:
            papers_to_process = papers_to_process[:1]
        else:
            print("No papers found in journal.yml.")

    print(f"Processing {len(papers_to_process)} paper(s)...")

    for paper in papers_to_process:
        repo_url = paper["repo"]
        main_file = paper["main_file"]
        repo_name = repo_url.split("/")[-1]
        if repo_name.endswith(".git"):
            repo_name = repo_name[:-4]
            
        clone_path = NEXUS_DIR / CONTENT_DIR / repo_name

        clone_repo(repo_url, clone_path)
        toc_entry = f"      - file: {CONTENT_DIR}/{repo_name}/{main_file}"
        toc_content.append(toc_entry)

    with open(TOC_FILE, "w") as f:
        f.write("\n".join(toc_content))

    print(f"Successfully generated {TOC_FILE} and cloned repos.")


if __name__ == "__main__":
    generate_toc()
